export const chuhaiList = [
    {
      janCode: "4904230013846",
      brand: "アサヒビール",
      name: "シードルスィート",
      volume: "200ml",
      alcohol: 3,
      sugarContent: "有糖",
      description:
        "国産リンゴ１００％でつくったスパークリングワインです。リンゴを丸ごと丁寧に搾った果汁から生まれました。",
    },
    {
      janCode: "4904230013860",
      brand: "アサヒビール",
      name: "シードルドライ",
      volume: "200ml",
      alcohol: 5,
      sugarContent: "有糖",
      description:
        "国産リンゴ１００％でつくったスパークリングワインです。リンゴを丸ごと丁寧に搾った果汁から生まれました。",
    },
    {
      janCode: "4904230059974",
      brand: "アサヒビール",
      name: "ニッカ　シードルロゼ",
      volume: "200ml",
      alcohol: 4,
      sugarContent: "有糖",
      description:
        "国産リンゴ１００％でつくったスパークリングワインです。リンゴを丸ごと丁寧に搾った果汁から生まれました。",
    },
    {
      janCode: "4901777403666",
      brand: "サントリーホールディ",
      name: "無添加ＳＰ赤泡Ｒ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description: "ぶどうをほおばったような果実感と心地よい炭酸感",
    },
    {
      janCode: "4901777403680",
      brand: "サントリーホールディ",
      name: "無添加ＳＰ白泡Ｒ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description: "ぶどうをほおばったような果実感と心地よい炭酸感",
    },
    {
      janCode: "4902102151429",
      brand: "日本コカ・コーラ",
      name: "ジャック＆コーク",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "有糖",
      description: "コカコーラとジャックダニエルのプレミックスカクテル",
    },
    {
      janCode: "4901880871932",
      brand: "サッポロビール",
      name: "男梅サワー",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description:
        "梅干しまるごと粉砕浸漬酒を使用した、唯一無二の梅干し感を味わえます。",
    },
    {
      janCode: "4985011710949",
      brand: "アシード",
      name: "愛南ゴールドのチューハイ",
      volume: "350ML",
      alcohol: 5,
      sugarContent: "有糖",
      description: "和製グレープフルーツと呼ばれている愛媛県の河内晩柑。",
    },
    {
      janCode: "4985011711243",
      brand: "アシード",
      name: "有田みかんのチューハイ",
      volume: "350ML",
      alcohol: 5,
      sugarContent: "有糖",
      description: "爽やかな酸味と有田特有の甘味でリフレッシュ。",
    },
    {
      janCode: "4901777201439",
      brand: "サントリー",
      name: "角ハイボール",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description:
        "炭酸強めの爽快な角ハイボールです。味わいの骨格となる原酒は角瓶と同じ原酒を使用しています。",
    },
    {
      janCode: "4901777349070",
      brand: "サントリーホールディ",
      name: "角ハイボール缶濃いめＲ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "ほのかなレモンピールの香りゆったり贅沢にお酒を味わえます",
    },
    {
      janCode: "4901777212008",
      brand: "サントリー",
      name: "トリスハイボール缶",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description:
        "トリスハイボールの特長であるすっきりとした味わいを生かしながら、レモンの風味を加えた爽やかな味わいが特長です。",
    },
    {
      janCode: "4901777306578",
      brand: "サントリー",
      name: "ジムビームハイボール缶",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description:
        "ジムビーム原酒の量を増やすことで、よりウイスキーのおいしさを感じられる香り・味わいを目指しました。爽快でキレのある中味に仕上げました。",
    },
    {
      janCode: "4901777375703",
      brand: "サントリーホールディ",
      name: "翠ジンソーダＲ",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "日常の食事に合う爽やかな味わいのサントリージン翠のソーダ割り",
    },
    {
      janCode: "4904670464543",
      brand: "宝酒造",
      name: "宝焼酎ハイボールレモン",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "スッキリとしたレモンの味わいが特長",
    },
    {
      janCode: "4904670464642",
      brand: "宝酒造",
      name: "宝焼酎ハイボールドライ",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description:
        "ガツンとくる辛口チューハイで、アルコール７%の飲みごたえが特徴。身体に嬉しい甘味料ゼロ、糖質80%オフ、プリン体ゼロを実現。甘くないので、どんな料理とも美味しくお飲みいただけます。",
    },
    {
      janCode: "4902102156189",
      brand: "日本コカ・コーラ",
      name: "甘くない檸檬堂無糖レモン７％",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description:
        "すっきりとした爽やかさ、みずみずしいレモンを存分に楽しめる、レモンをキュッと搾ったようなシンプルな味わいです。糖類・甘味料不使用。",
    },
    {
      janCode: "4902102156240",
      brand: "日本コカ・コーラ",
      name: "甘くない檸檬堂無糖レモン５％",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "無糖",
      description:
        "すっきりとした爽やかさ、みずみずしいレモンを存分に楽しめる、レモンをキュッと搾ったようなシンプルな味わいです。糖類・甘味料不使用。",
    },
    {
      janCode: "4901411104959",
      brand: "麒麟麦酒",
      name: "氷結無糖レモン４％Ｒ",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "無糖",
      description: "しっかりとした飲み応えキリッと冴えるレモンの果実味。",
    },
    {
      janCode: "4901411104898",
      brand: "麒麟麦酒",
      name: "氷結無糖レモン７％Ｒ",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "しっかりとした飲み応えキリッと冴えるレモンの果実味。",
    },
    {
      janCode: "4901411113678",
      brand: "麒麟麦酒",
      name: "氷結無糖ＧＦ４％３５０",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "無糖",
      description: "豊かなグレープフルーツの味わいかろやかな飲み心地。",
    },
    {
      janCode: "4901411113616",
      brand: "麒麟麦酒",
      name: "氷結無糖ＧＦ７％３５０",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "豊かなグレープフルーツの味わいかろやかな飲み心地。",
    },
    {
      janCode: "4904230073536",
      brand: "アサヒビール",
      name: "ＧＩＮＯＮレモンＲ缶",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description:
        "柑橘の果皮を漬け込んで蒸溜し、香味づけられたジンを使用。柑橘の風味がゆっくりと広がっていき、レモンの素材本来のおいしさを楽しむことができます。",
    },
    {
      janCode: "4904230073574",
      brand: "アサヒビール",
      name: "ＧＩＮＯＮ　ＧＦ　Ｒ缶",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description:
        "柑橘の果皮を漬け込んで蒸溜し、香味づけられたジンを使用。柑橘の風味がゆっくりと広がっていき、グレープフルーツの素材本来のおいしさを楽しむことができます。",
    },
    {
      janCode: "4901777423633",
      brand: "サントリーホールディ",
      name: "１９６無糖Ｗレモン４％Ｒ",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "無糖",
      description: "甘くなくすっきりとした食事に合う無糖のレモンチューハイ",
    },
    {
      janCode: "4901777393981",
      brand: "サントリーホールディ",
      name: "１９６瞬間凍結レモンＲ",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "甘くないのに骨太な果実感が愉しめる無糖レモン",
    },
    {
      janCode: "4901777409804",
      brand: "サントリーホールディ",
      name: "１９６無糖オレンジレモンＲ",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "無糖",
      description: "甘くなくすっきりとした無糖のオレンジ＆レモンチューハイ",
    },
    {
      janCode: "4989287001947",
      brand: "アシード",
      name: "太陽すもものチューハイ",
      volume: "350ML",
      alcohol: 4,
      sugarContent: "無糖",
      description: "深い甘みとほのかな酸味による爽やかでバランスの良い味わい。",
    },
    {
      janCode: "4936790540142",
      brand: "富永貿易",
      name: "カジューハイ　ピンクＧＦ",
      volume: "340ml",
      alcohol: 3,
      sugarContent: "無糖",
      description: "ピンクグレープフルーツ果汁１００％の低アルコール缶チューハイ",
    },
    {
      janCode: "4936790540166",
      brand: "富永貿易",
      name: "１００％カジューハイ白ぶどう",
      volume: "340ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "白ぶどう果汁１００％の低アルコール缶チューハイ",
    },
    {
      janCode: "4936790540128",
      brand: "富永貿易",
      name: "１００％カジューハイ　りんご",
      volume: "340ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "りんご果汁１００％の低アルコール缶チューハイ",
    },
    {
      janCode: "4560152543528",
      brand: "北海道麦酒醸造",
      name: "りんごのほっぺチューハイ",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description:
        "りんごの甘み、香り、美味しさを丸ごと凝縮した「りんごのほっぺ」を使用。",
    },
    {
      janCode: "4904230035480",
      brand: "アサヒビール",
      name: "カルピスサワー",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description:
        "「カルピス」の甘ずっぱいおいしさと程よいアルコール感が楽しめる、やさしくさわやかなスイート系缶チューハイです。甘ずっぱい味わいの「カルピス」をウオッカと炭ろ過水で仕上げたさわやかなスイート系缶チューハイです。",
    },
    {
      janCode: "4901411133959",
      brand: "麒麟麦酒",
      name: "華よい檸檬３５０",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "こころ華やぐ解放感を手軽に楽しめる果実スパークリング",
    },
    {
      janCode: "4901411133881",
      brand: "麒麟麦酒",
      name: "華よい白桃３５０",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "こころ華やぐ解放感を手軽に楽しめる果実スパークリング",
    },
    {
      janCode: "4901411133829",
      brand: "麒麟麦酒",
      name: "華よい葡萄３５０",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "こころ華やぐ解放感を手軽に楽しめる果実スパークリング",
    },
    {
      janCode: "4901777421141",
      brand: "サントリーホールディ",
      name: "ほろよいレモンティーＲ",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "華やかな紅茶にレモンが爽やかさを添える味わい",
    },
    {
      janCode: "4901777421165",
      brand: "サントリーホールディ",
      name: "ほろよいアップルティーＲ",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "紅茶とアップルの華やかさが楽しめる味わい",
    },
    {
      janCode: "4901777375505",
      brand: "サントリーホールディ",
      name: "ほろよいレモみかんＲ",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "レモンの爽やかさとみかんのやさしい甘みを楽しめるほろよいです",
    },
    {
      janCode: "4901777284791",
      brand: "サントリー",
      name: "ほろよい　白ぶどう",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description:
        "白ぶどうのみずみずしい果実感が口いっぱいに広がる、さわやかな味わいです。",
    },
    {
      janCode: "4901777196698",
      brand: "サントリー",
      name: "ほろよいもも",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "圧倒的な桃の果実味",
    },
    {
      janCode: "4901777204706",
      brand: "サントリー",
      name: "ほろよい白いサワー",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description:
        "乳性飲料のようなやさしい味わいはそのままに、甘酸っぱい爽やかさをより感じられる中味に仕上げました。",
    },
    {
      janCode: "4901777247277",
      brand: "サントリー",
      name: "カシスとオレンジ",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description:
        "オレンジ果汁の味わいがしっかりと感じられるフルーティな味わいに仕上げました。カシスのほどよい甘酸っぱさと微炭酸による爽やかな飲み心地。",
    },
    {
      janCode: "4901777360136",
      brand: "サントリーホールディ",
      name: "ほろよいシュワビタＲ",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "シュワシュワした炭酸が心地良い　心が前向きになれるほろよい",
    },
    {
      janCode: "4901777193369",
      brand: "サントリー",
      name: "ほろよい梅酒ソーダ",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "人気上昇中の梅",
    },
    {
      janCode: "4901411000459",
      brand: "キリンビール",
      name: "キリンビール　氷結レモン",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description:
        "シチリア島で収穫されたレモンを主に使用した、みずみずしくスッキリ爽快なおいしさ。",
    },
    {
      janCode: "4901411025896",
      brand: "キリンビール",
      name: "キリン本搾りチューハイレモン",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "糖類無添加の果実系チューハイ",
    },
    {
      janCode: "4901411026152",
      brand: "キリンビール",
      name: "キリン本搾りチューハイＧＦ",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "糖類無添加の果実系チューハイ",
    },
    {
      janCode: "4901411055480",
      brand: "キリンビール",
      name: "本搾りピンクグレープフルーツ",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description:
        "果実とお酒だけでつくる、ピンクグレープフルーツを主に使用した、フルーティなおいしさが楽しめるチューハイ。",
    },
    {
      janCode: "4901411039985",
      brand: "キリンビール",
      name: "本搾りオレンジ",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description:
        "果実とお酒だけでつくる、オレンジのジューシーなおいしさが楽しめるチューハイ。",
    },
    {
      janCode: "4904230052289",
      brand: "アサヒビール（株）",
      name: "贅沢搾りグレープフルーツ",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "有糖",
      description: "アサヒ贅沢搾りグレープフルーツ",
    },
    {
      janCode: "4904230052326",
      brand: "アサヒビール（株）",
      name: "贅沢搾り桃",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "有糖",
      description: "贅沢搾り桃",
    },
    {
      janCode: "4904230067252",
      brand: "アサヒビール",
      name: "贅沢搾りプレミアムみかん",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "有糖",
      description: "果実感たっぷりの味わいの贅沢なみかんテイストチューハイです。",
    },
    {
      janCode: "4904230073192",
      brand: "アサヒビール",
      name: "贅沢搾りプレミアムぶどう",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "有糖",
      description: "果実感たっぷりの味わいが楽しめる贅沢なぶどうチューハイです",
    },
    {
      janCode: "4901777393882",
      brand: "サントリーホールディ",
      name: "こだわり酒場タコハイＲ",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "酒場で愛されるプレーンサワー「タコハイ」",
    },
    {
      janCode: "4901777332508",
      brand: "サントリーホールディ",
      name: "こだわりレモンサワーＲ",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "有糖",
      description: "しっかりレモン感とお酒のうまみを楽しめる新しいレモンサワー",
    },
    {
      janCode: "4901777361607",
      brand: "サントリーホールディ",
      name: "こだわり酒場追足Ｒ",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "レモンにひと工夫したお店のうまいレモンサワー",
    },
    {
      janCode: "4901880201371",
      brand: "サッポロビール",
      name: "濃いめのレモンサワー",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "有糖",
      description: "レモン味しっかり濃いめのレモンサワー",
    },
    {
      janCode: "4901880205102",
      brand: "サッポロビール",
      name: "濃いめ濃いままＲ",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "レモン味濃いめのしっかりすっぱいレモンサワーの濃いまま５度",
    },
    {
      janCode: "4901880209940",
      brand: "サッポロビール",
      name: "濃いめグレフルＲ",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "有糖",
      description: "グレフル味濃いめのグレフルサワー",
    },
    {
      janCode: "4901880208226",
      brand: "サッポロビール",
      name: "ニッポンのシンレモンＲ",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "レモンのプロのポッカサッポロと協働開発レモンサワーのシン定番",
    },
    {
      janCode: "4902102130189",
      brand: "日本コカ・コーラ",
      name: "檸檬堂　定番レモン缶",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "丸ごとすりおろしレモン果汁　ＡＬＣ５％果汁１０％　定番の味",
    },
    {
      janCode: "4902102155076",
      brand: "日本コカ・コーラ",
      name: "檸檬堂　レモン濃いめ",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "有糖",
      description: "レモン丸ごと２個分のたっぷりレモンとお酒の超濃厚レモンサワー",
    },
    {
      janCode: "4549414440751",
      brand: "イオントップバリュ",
      name: "ＢＰレモンサワー３５０",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "有糖",
      description: "しっかり　とした飲み応えキリッ　と冴えるレモンの果実味。",
    },
    {
      janCode: "4549414625820",
      brand: "イオントップバリュ",
      name: "ＢＰカロリーハーフレモン",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "カロリー半分糖類８０オフのすっきりした味わいのチューハイ",
    },
    {
      janCode: "4549414440638",
      brand: "イオントップバリュ",
      name: "ＢＰまる搾りレモン３５０",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "レモンの果実をまるごと搾った果汁感たっぷりのチューハイ",
    },
    {
      janCode: "4549414440676",
      brand: "イオントップバリュ",
      name: "ＢＰまる搾りＧＦ３５０",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "グレープフルーツをまるごと搾った果汁感たっぷりのチューハイ",
    },
    {
      janCode: "4549414440713",
      brand: "イオントップバリュ",
      name: "ＢＰまるごとうめ３５０",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "国産梅１００％使用した梅酒の芳醇な味わいをお楽しみください。",
    },
    {
      janCode: "4549414448689",
      brand: "イオントップバリュ",
      name: "ＢＰＳＴぶどう３５０ｍｌ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description: "糖類ゼロプリン体ゼロの果実の味が感じられるチューハイです！",
    },
    {
      janCode: "4549414448764",
      brand: "イオントップバリュ",
      name: "ＢＰＳＴライム３５０ｍｌ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description: "糖類ゼロプリン体ゼロの果実の味が感じられるチューハイです！",
    },
    {
      janCode: "4549414629255",
      brand: "イオントップバリュ",
      name: "ＢＰ無糖プレーン３５０",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "糖類・甘味料を一切使わず仕上げた余計な甘さのない味わい",
    },
    {
      janCode: "4549414623895",
      brand: "イオントップバリュ",
      name: "ＢＰ無糖レモン３５０ｍｌ",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "糖類・甘味料を一切使わず仕上げた余計な甘さのない味わい",
    },
    {
      janCode: "4549414623932",
      brand: "イオントップバリュ",
      name: "ＢＰ無糖ＧＦ３５０ｍｌ",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "糖類・甘味料を一切使わず仕上げた余計な甘さのない味わい",
    },
    {
      janCode: "4549414631159",
      brand: "イオントップバリュ",
      name: "ＢＰ無糖シークァー３５０",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "糖類・甘味料を一切使わず仕上げた余計な甘さのない味わい",
    },
    {
      janCode: "4549414609264",
      brand: "イオントップバリュ",
      name: "ＢＰウィスキーハイボール",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "本場スコットランドで蒸留されたウィスキーのハイボール",
    },
    {
      janCode: "4549414448726",
      brand: "イオントップバリュ",
      name: "ＢＰＳＴドライ３５０ｍｌ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "糖類ゼロプリン体ゼロの高炭酸チューハイです。！",
    },
    {
      janCode: "4549414448603",
      brand: "イオントップバリュ",
      name: "ＢＰＳＴレモン３５０ｍｌ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "糖類ゼロプリン体ゼロの果実の味が感じられるチューハイです！",
    },
    {
      janCode: "4549414448801",
      brand: "イオントップバリュ",
      name: "ＢＰＳＴ塩レモン３５０",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "糖類ゼロプリン体ゼロの果実の味が感じられるチューハイです！",
    },
    {
      janCode: "4549414448641",
      brand: "イオントップバリュ",
      name: "ＢＰＳＴＧＦ３５０ｍｌ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "糖類ゼロプリン体ゼロの果実の味が感じられるチューハイです！",
    },
    {
      janCode: "4549414623970",
      brand: "イオントップバリュ",
      name: "ＢＰＳＴうめ３５０ｍｌ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "糖類ゼロプリン体ゼロの果実の味が感じられるチューハイです！",
    },
    {
      janCode: "4901777026001",
      brand: "サントリー",
      name: "サントリー　白角水割",
      volume: "250ml",
      alcohol: 9,
      sugarContent: "無糖",
      description:
        "爽やかな香味とすっきりキレの良いあとくちが特長の水割りウイスキーです。",
    },
    {
      janCode: "4905846118468",
      brand: "チョーヤ梅酒",
      name: "ウメッシュ３％缶",
      volume: "250ml",
      alcohol: 3,
      sugarContent: "無糖",
      description: "すっきりとしたライトな飲み心地の本格梅酒ソーダ",
    },
    {
      janCode: "4905846111360",
      brand: "チョーヤ",
      name: "チョーヤ　ウメッシュ　缶",
      volume: "250ml",
      alcohol: 4,
      sugarContent: "有糖",
      description:
        "酸味料や香料を使用せず、梅のエキスをじっくりと抽出した本格梅酒のソーダ割りだから飲み飽きしないおいしさが楽しめます。",
    },
    {
      janCode: "4905846117065",
      brand: "チョーヤ梅酒",
      name: "チョーヤ　ゆずッシュ",
      volume: "250ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "四国産ゆず使用のすっきり爽やかな味わい。",
    },
    {
      janCode: "4905846118444",
      brand: "チョーヤ梅酒",
      name: "熟成一年梅酒ソーダ　缶",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "Ｔｈｅ　ＣＨＯＹＡ熟成一年をそのままソーダ割りにしました",
    },
    {
      janCode: "4971980755593",
      brand: "合同酒精",
      name: "ＮＰシャインマスカット",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "甘くて芳醇な味わいとぶどう感たっぷりなマスカットチューハイ",
    },
    {
      janCode: "4971980310709",
      brand: "合同酒精",
      name: "合同　沖縄県産パイナップル",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description:
        "沖縄の太陽をたっぷり浴びて熟した、厳選パイナップル果汁を使用。甘酸っぱくてジューシーなチューハイです。",
    },
    {
      janCode: "4942568140018",
      brand: "山形県酒類卸",
      name: "木頭ゆずチューハイ",
      volume: "350ML",
      alcohol: 3,
      sugarContent: "有糖",
      description: "ＪＡアグリあなん女性部が感性を活かして開発したチューハイ",
    },
    {
      janCode: "4901880880989",
      brand: "サッポロビール",
      name: "超男梅サワー",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description:
        "梅干しまるごとの旨さを閉じ込めた液中粉砕浸漬酒を使用。アルコール９度の飲みごたえと、こだわり抜いた梅干し感をお楽しみください。",
    },
    {
      janCode: "4901880207182",
      brand: "サッポロビール",
      name: "男梅サワー無糖Ｒ",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "無糖",
      description: "食事に合う男梅サワーウメぇ無糖が新登場",
    },
    {
      janCode: "4901411130651",
      brand: "麒麟麦酒",
      name: "上々焼酎ソーダ梅３５０",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "梅干しをアクセントに加えたスッキリ爽やかで軽快な焼酎ソーダ",
    },
    {
      janCode: "4901411121659",
      brand: "麒麟麦酒",
      name: "上々焼酎ソーダＲ",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "最高の食中酒となる軽快な飲み口のキリンの焼酎ソーダ",
    },
    {
      janCode: "4904670470681",
      brand: "宝酒造",
      name: "宝　焼酎のやわらかお茶割り",
      volume: "335ml",
      alcohol: 4,
      sugarContent: "無糖",
      description: "こだわりの茶葉使用香料・着色料不使用プリン体ゼロ",
    },
    {
      janCode: "4904670479066",
      brand: "宝酒造",
      name: "宝焼酎の濃いお茶割り",
      volume: "335ML",
      alcohol: 4,
      sugarContent: "無糖",
      description: "カテキン２倍で渋くて濃い味わいが特長の濃いお茶割り。",
    },
    {
      janCode: "4901777411227",
      brand: "サントリーホールディ",
      name: "茉莉花ジャスミン茶割",
      volume: "335ml",
      alcohol: 4,
      sugarContent: "無糖",
      description: "ジャスミン焼酎茉莉花をジャスミン茶で割った通称ＪＪ缶",
    },
    {
      janCode: "4901777180918",
      brand: "サントリー",
      name: "ＳＵ烏龍チューハイ",
      volume: "335ml",
      alcohol: 4,
      sugarContent: "無糖",
      description: "中国福建省産の茶葉を使用",
    },
    {
      janCode: "4901777218581",
      brand: "サントリー",
      name: "ほろよいはちみつレモン",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description:
        "レモンのほどよい酸味に、はちみつのやさしい甘さを加えた爽やかな味わいです。",
    },
    {
      janCode: "4901777214590",
      brand: "サントリー",
      name: "ＳＵほろよいアイスティーＳ",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description:
        "紅茶の華やかな香りとほのかなレモンの味わいが楽しめる、すっきりとした味わいです。",
    },
    {
      janCode: "4901777211742",
      brand: "サントリー",
      name: "ほろよい　ぶどう",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "有糖",
      description: "やわらかい甘みと華やかな香りアルコール３％やさしい飲み心地",
    },
    {
      janCode: "4901411121451",
      brand: "麒麟麦酒",
      name: "本搾りプレミアム４種Ｒ",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "有糖",
      description: "複数果実のブレンドと果実の余韻が楽しめる特別な本搾り",
    },
    {
      janCode: "4901411121499",
      brand: "麒麟麦酒",
      name: "本搾りプレミアム３種Ｒ",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "複数果実のブレンドと果実の余韻が楽しめる特別な本搾り",
    },
    {
      janCode: "4904230070238",
      brand: "アサヒビール",
      name: "贅沢プレミアムトマトＲ",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "有糖",
      description: "果実感たっぷりの味わいが楽しめる贅沢なトマトチューハイです。",
    },
    {
      janCode: "4901411101446",
      brand: "麒麟麦酒",
      name: "キリンザストロングレモンＲ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description: "本格的なレモンの甘すぎない味わい。追いレモン潤沢仕立て。",
    },
    {
      janCode: "4901411101576",
      brand: "麒麟麦酒",
      name: "キリンザストロングホワイトＲ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description: "すっきり飲みやすい爽快な味わい。ヨーグルトすっきり仕立て。",
    },
    {
      janCode: "4901880209803",
      brand: "サッポロビール",
      name: "クラフトスパイスソーダＲ",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "食事を引き立てる香りと刺激",
    },
    {
      janCode: "4901411134390",
      brand: "麒麟麦酒",
      name: "Ｐジンソーダ杜の香３５０",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "ジュニパーベリー１００％のジンの清涼感と軽やかな炭酸感",
    },
    {
      janCode: "4904230044994",
      brand: "アサヒビール",
      name: "ブラックニッカハイボール",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "ブラックニッカハイボール",
    },
    {
      janCode: "4904230051657",
      brand: "アサヒビール（株）",
      name: "ＢＬＣハイボール香る夜",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "ＢＬＣハイボール香る夜缶",
    },
    {
      janCode: "4904670495103",
      brand: "宝酒造",
      name: "宝発酵蒸留サワークリア",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "無糖",
      description: "お酒好きのための３％チューハイ",
    },
    {
      janCode: "4904670496346",
      brand: "宝酒造",
      name: "宝発酵蒸留サワーレモン",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "無糖",
      description: "お酒好きのための３％チューハイ",
    },
    {
      janCode: "4904670495721",
      brand: "宝酒造",
      name: "宝発酵蒸留サワーぶどう",
      volume: "350ml",
      alcohol: 3,
      sugarContent: "無糖",
      description: "お酒好きのための３％チューハイ",
    },
    {
      janCode: "4901411110844",
      brand: "麒麟麦酒",
      name: "氷結無糖レモン９％３５０缶",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "甘くないスッキリ爽快なおいしさの無糖レモンチューハイ",
    },
    {
      janCode: "4901411122052",
      brand: "麒麟麦酒",
      name: "氷結無糖シークヮーサー７％Ｒ",
      volume: "350ml",
      alcohol: 7,
      sugarContent: "無糖",
      description: "甘くないスッキリ爽快なおいしさの無糖チューハイ",
    },
    {
      janCode: "4901777404786",
      brand: "サントリーホールディ",
      name: "１９６瞬間無糖グレフルＲ",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "甘くないのに骨太な果実感が愉しめる無糖グレフル",
    },
    {
      janCode: "4901777409767",
      brand: "サントリーホールディ",
      name: "１９６無糖シークヮーサーＲ",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "無糖",
      description: "甘くなくすっきりとした無糖のシークヮーサーチューハイ",
    },
    {
      janCode: "4901777374317",
      brand: "サントリーホールディ",
      name: "こだわり酒場濃い旨Ｒ",
      volume: "350ml",
      alcohol: 6,
      sugarContent: "有糖",
      description: "レモンが濃くて晩酌がうまいお店のレモンサワー",
    },
    {
      janCode: "4901411000404",
      brand: "キリンビール",
      name: "キリンビール　氷結ＧＦ",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description:
        "ホワイトとルビーのグレープフルーツを使用した、みずみずしくスッキリ爽快なおいしさ。",
    },
    {
      janCode: "4901411034683",
      brand: "キリンビール",
      name: "氷結シャルドネスパークリング",
      volume: "350ml",
      alcohol: 5,
      sugarContent: "有糖",
      description: "上品に香るシャルドネの、みずみずしくフルーティなおいしさ。",
    },
    {
      janCode: "4904230053644",
      brand: "アサヒビール（株）",
      name: "贅沢搾りキウイ",
      volume: "350ml",
      alcohol: 4,
      sugarContent: "有糖",
      description: "贅沢搾りキウイ",
    },
    {
      janCode: "4901777240971",
      brand: "サントリー",
      name: "１９６ＤＲＹ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description:
        "当社独自のウオツカやラムなど、厳選した原料酒を絶妙なバランスで配合し、甘くない爽快なキレ味を実現しました。",
    },
    {
      janCode: "4901777192607",
      brand: "サントリー",
      name: "ー１９６℃ストロングＤレモン",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description: "ダブルレモンの果実感ダブルレモンの果実感",
    },
    {
      janCode: "4901777293656",
      brand: "サントリー",
      name: "ー１９６ＳＴビターレモン",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description:
        "ほろ苦さを引き出したレモンピール（果皮）浸漬酒とレモンまるごとの浸漬酒を使用し、レモン果皮本来のほろ苦さが楽しめる甘くないすっきりとした味わいに仕上げました。",
    },
    {
      janCode: "4901777210912",
      brand: "サントリー",
      name: "１９６ゼロシークワーサー",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description:
        "－196℃製法による果実の浸漬酒と果汁をダブルで使用しました。しっかりとした飲みごたえと果実感を楽しめます。",
    },
    {
      janCode: "4901777222861",
      brand: "サントリー",
      name: "１９６ＳＺ完熟梅",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "有糖",
      description:
        "-196℃製法による完熟梅の浸漬酒と完熟梅酒をダブルで使用しました。",
    },
    {
      janCode: "4901777371613",
      brand: "サントリーホールディ",
      name: "レモンハイトリスＲ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description: "漬け込みレモンをウイスキーで丁寧に仕上げた特製ハイボール",
    },
    {
      janCode: "4901777285040",
      brand: "サントリー",
      name: "トリハイ缶　キリッと濃いめ",
      volume: "350ml",
      alcohol: 9,
      sugarContent: "無糖",
      description:
        "中味の配合バランスを見直すことで、よりウイスキーの飲みごたえと余韻を感じられ、満足感がありながらもすっきりと飲み飽きないおいしさになりました。",
    },
  ];
  